# Generated by Django 4.2.8 on 2025-10-21 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(help_text="Description de l'image à générer"),
                ),
                (
                    "negative_prompt",
                    models.TextField(
                        blank=True, help_text="Éléments à éviter dans l'image"
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "image_file",
                    models.ImageField(
                        blank=True, null=True, upload_to="generated_images/%Y/%m/%d/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="thumbnails/%Y/%m/%d/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("generating", "En cours de génération"),
                            ("generated", "Générée"),
                            ("validated", "Validée"),
                            ("rejected", "Rejetée"),
                            ("failed", "Échec"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("style", models.CharField(default="realistic", max_length=100)),
                ("width", models.IntegerField(default=1024)),
                ("height", models.IntegerField(default=1024)),
                ("quality", models.CharField(default="standard", max_length=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "generation_time",
                    models.FloatField(
                        blank=True,
                        help_text="Temps de génération en secondes",
                        null=True,
                    ),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("validation_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Image",
                "verbose_name_plural": "Generated Images",
                "db_table": "generated_images",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImageTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Image Tag",
                "verbose_name_plural": "Image Tags",
                "db_table": "image_tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ImageGenerationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="images.generatedimage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Image Generation History",
                "verbose_name_plural": "Image Generation Histories",
                "db_table": "image_generation_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImageTagRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_relations",
                        to="images.generatedimage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_relations",
                        to="images.imagetag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image Tag Relation",
                "verbose_name_plural": "Image Tag Relations",
                "db_table": "image_tag_relations",
                "unique_together": {("image", "tag")},
            },
        ),
        migrations.AddIndex(
            model_name="generatedimage",
            index=models.Index(
                fields=["user", "-created_at"], name="generated_i_user_id_b538cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedimage",
            index=models.Index(fields=["status"], name="generated_i_status_d3f65f_idx"),
        ),
    ]
