# Generated by Django 4.2.8 on 2025-10-21 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        help_text="Date et heure de publication prévue"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("linkedin", "LinkedIn"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "caption",
                    models.TextField(help_text="Légende du post", max_length=2200),
                ),
                (
                    "hashtags",
                    models.TextField(
                        blank=True, help_text="Hashtags (séparés par des espaces)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Planifié"),
                            ("processing", "En cours de publication"),
                            ("posted", "Publié"),
                            ("failed", "Échec"),
                            ("cancelled", "Annulé"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "platform_post_id",
                    models.CharField(
                        blank=True,
                        help_text="ID du post sur la plateforme",
                        max_length=200,
                    ),
                ),
                (
                    "platform_post_url",
                    models.URLField(
                        blank=True, help_text="URL du post publié", max_length=500
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_posts",
                        to="images.generatedimage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Post",
                "verbose_name_plural": "Scheduled Posts",
                "db_table": "scheduled_posts",
                "ordering": ["scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="PostingSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Nom du planning", max_length=100)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Quotidien"),
                            ("weekly", "Hebdomadaire"),
                            ("monthly", "Mensuel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("time_of_day", models.TimeField(help_text="Heure de publication")),
                (
                    "weekday",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ],
                        help_text="Jour de la semaine (pour planning hebdomadaire)",
                        null=True,
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True,
                        help_text="Jour du mois (pour planning mensuel, 1-31)",
                        null=True,
                    ),
                ),
                (
                    "platforms",
                    models.JSONField(
                        default=list, help_text="Liste des plateformes pour ce planning"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posting_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Posting Schedule",
                "verbose_name_plural": "Posting Schedules",
                "db_table": "posting_schedules",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PostAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("likes", models.IntegerField(default=0)),
                ("comments", models.IntegerField(default=0)),
                ("shares", models.IntegerField(default=0)),
                ("views", models.IntegerField(default=0)),
                ("reach", models.IntegerField(default=0)),
                ("impressions", models.IntegerField(default=0)),
                ("engagement_rate", models.FloatField(default=0.0)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scheduled_post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="scheduler.scheduledpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Analytics",
                "verbose_name_plural": "Post Analytics",
                "db_table": "post_analytics",
            },
        ),
        migrations.AddIndex(
            model_name="scheduledpost",
            index=models.Index(
                fields=["user", "scheduled_time"], name="scheduled_p_user_id_dfcd3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledpost",
            index=models.Index(
                fields=["status", "scheduled_time"],
                name="scheduled_p_status_39a7aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledpost",
            index=models.Index(
                fields=["platform"], name="scheduled_p_platfor_0915b8_idx"
            ),
        ),
    ]
